# Generated by Django 4.2 on 2023-04-30 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_rental_rental_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
