# Generated by Django 4.2 on 2023-05-04 10:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=django_countries.fields.CountryField(max_length=50),
        ),
    ]
